development:
  adapter: jdbcmysql
  database: geograph_development
  reconnect: false
  pool: 20
  username: root
  password: hokuto

test:
  adapter: jdbcmysql
  database: geograph_test
  reconnect: false
  pool: 20
  username: root
  password: geograph

production:
  adapter: mysql
  database: geograph_development
  host: localhost
  username: root
  password: hokuto
  encoding: utf8
