development:
  adapter: jdbcmysql
  database: geograph_development
  reconnect: false
  pool: 20
  username: root
  password: geograph

test:
  adapter: jdbcmysql
  database: geograph_test
  reconnect: false
  pool: 20
  username: root
  password: geograph


production:
  adapter: jdbcmysql
  database: geograph_production
  host: 10.100.0.1
  reconnect: false
  pool: 20
  username: root
  password: geograph


