---
development:
  adapter: mysql
  database: geograph_development
  host: localhost
  username: root
  password: geograph
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: geograph_production
  host: 10.100.0.1
  username: geograph
  password: geograph_passwd
  encoding: utf8

