messaging:
  /queue/commands:
    Madmass::Agent::JmsExecutor:
      selector: "perception IS NULL AND ((synchronous IS NULL) OR (synchronous <> 'true'))"
      concurrency: 4
    Madmass::Agent::SyncJmsExecutor:
      selector: "perception IS NULL AND synchronous = 'true'"
      concurrency: 8

#

topics:
  /topic/perceptions:

queues:
  /queue/commands:
    durable: false


#services:
#  StatsService:
#    config:
#      sleep: 5

#jobs:
#   edges.processor:
#     job:  EdgesProcessor
#     cron: '*/30 * * * * ?'
#     description:  Process edges for all geo objects
#     singleton: true

#stomp:
#  stomplets:
#    test_stomplet:
#      class: Madmass::CommandsStomplet
#      route: '/madmass/domain'
#      config:
#        perceptions_destination: /topic/perceptions
#        commands_destination: /queue/commands


#tasks:
#  Backgroundable:
#    concurrency: 500

pooling:
  messaging:
    type: shared
    lazy: true
  web:
    type: shared
    lazy: true
  jobs:
    type: shared
    lazy: true

ruby:
  version: 1.9
  compile_mode: jit
  debug: false
  interactive: false
  profile_api: false
